# Generated by Django 5.2.15 on 2026-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrlevel',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
