# Generated by Django 5.2.15 on 2026-07-05 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_alter_cefrlevel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('cefr_label', models.CharField(max_length=10)),
                ('blurb', models.CharField(max_length=300)),
                ('stage', models.CharField(choices=[('beginner', 'Beginner'), ('independent', 'Independent'), ('expert', 'Expert')], max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('mcq', 'Multiple choice'), ('gap', 'Fill the gap'), ('transform', 'Transformation')], max_length=10)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(default=list)),
                ('why', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vocab.grammartopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarLessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('intro', 'Intro'), ('rule', 'Rule'), ('table', 'Table'), ('examples', 'Examples'), ('tip', 'Tip')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='vocab.grammartopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
