# Generated by Django 5.2.15 on 2026-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_grammartopic_grammarquestion_grammarlessonblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammartopic',
            name='stage',
            field=models.CharField(choices=[('beginner', 'Basic'), ('independent', 'Intermediate'), ('expert', 'Advanced')], max_length=12),
        ),
    ]
