/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--color-bg) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        surface2: "rgb(var(--color-surface2) / <alpha-value>)",
        line: "rgb(var(--color-line) / <alpha-value>)",
        ink: "rgb(var(--color-ink) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        b1: "rgb(var(--color-b1) / <alpha-value>)",
        b2: "rgb(var(--color-b2) / <alpha-value>)",
        c1: "rgb(var(--color-c1) / <alpha-value>)",
        c2: "rgb(var(--color-c2) / <alpha-value>)",
        c2p: "rgb(var(--color-c2p) / <alpha-value>)",
        tb: "#3b82f6",
        tv: "#8b5cf6",
        tp: "#ec4899",
        tr: "#ef4444",
        te: "#10b981",
        ta: "#f59e0b",
        tc: "#06b6d4",
        tg: "#eab308",
        ti: "#6366f1",
        to: "#f97316",
        tro: "#f43f5e",
        tfg: "#16a34a",
        tpurp: "#a855f7",
        ts: "#0d9488",
      },
      fontFamily: {
        sora: ["Sora", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
