# Generated by Django 5.2.15 on 2026-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_cefr_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrlevel',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
