import django.db.models.deletion
from django.db import migrations, models

SECTIONS = [
    ('essential-verbs', 'Essential Verbs', 'basic'),
    ('people-relationships', 'People & Relationships', 'basic'),
    ('mind-feelings', 'Mind & Feelings', 'basic'),
    ('home-daily-life', 'Home & Daily Life', 'basic'),
    ('the-natural-world', 'The Natural World', 'basic'),
    ('body-health', 'Body & Health', 'basic'),
    ('out-about', 'Out & About', 'basic'),
    ('time-description', 'Time & Description', 'basic'),
    ('numbers-learning', 'Numbers & Learning', 'basic'),
    ('sports-hobbies', 'Sports & Hobbies', 'basic'),
    ('emotions-in-depth', 'Emotions in Depth', 'intermediate'),
    ('personality-character', 'Personality & Character', 'intermediate'),
    ('mind-behaviour-psychology', 'Mind, Behaviour & Psychology', 'intermediate'),
    ('society-social-issues', 'Society & Social Issues', 'intermediate'),
    ('work-career', 'Work & Career', 'intermediate'),
    ('education-society', 'Education & Society', 'intermediate'),
    ('economics-finance', 'Economics & Finance', 'intermediate'),
    ('politics-global-affairs', 'Politics & Global Affairs', 'intermediate'),
    ('environment-climate', 'Environment & Climate', 'intermediate'),
    ('health-medicine', 'Health & Medicine', 'intermediate'),
    ('science-innovation', 'Science & Innovation', 'intermediate'),
    ('technology-media', 'Technology & Media', 'intermediate'),
    ('media-journalism', 'Media & Journalism', 'intermediate'),
    ('cities-urban-life', 'Cities & Urban Life', 'intermediate'),
    ('travel-culture-society', 'Travel, Culture & Society', 'intermediate'),
    ('food-nutrition-culture', 'Food, Nutrition & Culture', 'intermediate'),
    ('arts-media-culture', 'Arts, Media & Culture', 'intermediate'),
    ('language-communication', 'Language & Communication', 'intermediate'),
    ('action-process-verbs', 'Action & Process Verbs', 'intermediate'),
    ('quality-degree-adjectives', 'Quality & Degree Adjectives', 'intermediate'),
    ('idioms-collocations', 'Idioms & Collocations', 'intermediate'),
    ('connectors-discourse-markers', 'Connectors & Discourse Markers', 'intermediate'),
    ('academic-language-writing', 'Academic Language & Writing', 'intermediate'),
    ('verbs-for-writing-analysis', 'Verbs for Writing & Analysis', 'intermediate'),
    ('precision-control-vocabulary', 'Precision & Control Vocabulary', 'intermediate'),
    ('b2-noun-bank', 'B2 Noun Bank', 'intermediate'),
    ('b2-milestone-sets', 'B2 Milestone Sets', 'intermediate'),
    ('negative-qualities-criticism', 'Negative Qualities & Criticism', 'advanced'),
    ('positive-qualities-strength', 'Positive Qualities & Strength', 'advanced'),
    ('mind-emotion-description', 'Mind, Emotion & Description', 'advanced'),
    ('scale-change-society', 'Scale, Change & Society', 'advanced'),
    ('academic-writing-toolkit', 'Academic Writing Toolkit', 'advanced'),
    ('formal-english-fixed-expressions', 'Formal English & Fixed Expressions', 'advanced'),
    ('ielts-writing-themes-i', 'IELTS Writing Themes I', 'advanced'),
    ('ielts-writing-themes-ii', 'IELTS Writing Themes II', 'advanced'),
    ('academic-writing-toolkit-ii', 'Academic Writing Toolkit II', 'advanced'),
    ('vivid-description-communication', 'Vivid Description & Communication', 'advanced'),
    ('cognition-logic-research', 'Cognition, Logic & Research', 'advanced'),
    ('academic-connectors-iii', 'Academic Connectors III', 'advanced'),
    ('career-business-leadership', 'Career, Business & Leadership', 'advanced'),
    ('workplace-tasks-formal-language', 'Workplace Tasks & Formal Language', 'advanced'),
    ('governance-economy-society', 'Governance, Economy & Society', 'advanced'),
    ('personality-relationships-conflict', 'Personality, Relationships & Conflict', 'advanced'),
    ('everyday-life-money-idioms', 'Everyday Life, Money & Idioms', 'advanced'),
    ('science-tech-innovation', 'Science, Tech & Innovation', 'advanced'),
    ('nature-climate-energy', 'Nature, Climate & Energy', 'advanced'),
    ('travel-culture-urban-life', 'Travel, Culture & Urban Life', 'advanced'),
    ('lifestyle-leisure-wellbeing', 'Lifestyle, Leisure & Wellbeing', 'advanced'),
    ('storytelling-humour-persuasion', 'Storytelling, Humour & Persuasion', 'advanced'),
    ('description-size-sound-movement', 'Description: Size, Sound & Movement', 'advanced'),
    ('habits-comparison-politeness', 'Habits, Comparison & Politeness', 'advanced'),
    ('mind-abstract-thought', 'Mind & Abstract Thought', 'advanced'),
    ('society-rights-change', 'Society, Rights & Change', 'advanced'),
    ('global-power-economy', 'Global Power & Economy', 'advanced'),
    ('philosophy-critical-thought', 'Philosophy & Critical Thought', 'advanced'),
    ('arts-history-culture', 'Arts, History & Culture', 'advanced'),
    ('science-research-medicine', 'Science, Research & Medicine', 'advanced'),
    ('academic-register-style', 'Academic Register & Style', 'advanced'),
    ('precision-literary-language', 'Precision & Literary Language', 'advanced'),
    ('advanced-adjectives', 'Advanced Adjectives', 'advanced'),
    ('advanced-verbs-nouns', 'Advanced Verbs & Nouns', 'advanced'),
    ('formal-nouns-qualifiers', 'Formal Nouns & Qualifiers', 'advanced'),
    ('ielts-essay-mastery', 'IELTS Essay Mastery', 'advanced'),
    ('advanced-lexical-expansion', 'Advanced Lexical Expansion', 'advanced'),
    ('c2-finishing-sets', 'C2 Finishing Sets', 'advanced'),
]

CATEGORY_SECTIONS = {
    'neg-intensity': 'Negative Qualities & Criticism',
    'deception-falsehood': 'Negative Qualities & Criticism',
    'judgment-criticism': 'Negative Qualities & Criticism',
    'weakness-deterioration': 'Negative Qualities & Criticism',
    'approval-excellence': 'Positive Qualities & Strength',
    'strength-persistence': 'Positive Qualities & Strength',
    'support-agreement': 'Positive Qualities & Strength',
    'ethics-morality': 'Positive Qualities & Strength',
    'emotions-psych': 'Mind, Emotion & Description',
    'appearance-character': 'Mind, Emotion & Description',
    'tone-atmosphere': 'Mind, Emotion & Description',
    'thinking-intelligence': 'Mind, Emotion & Description',
    'scope-scale': 'Scale, Change & Society',
    'magnitude-impact': 'Scale, Change & Society',
    'change-transformation': 'Scale, Change & Society',
    'society-politics': 'Scale, Change & Society',
    'clarity-certainty': 'Academic Writing Toolkit',
    'academic-stance': 'Academic Writing Toolkit',
    'connectors-transitions': 'Academic Writing Toolkit',
    'linking-words': 'Academic Writing Toolkit',
    'professional-register': 'Formal English & Fixed Expressions',
    'abstract-nouns': 'Formal English & Fixed Expressions',
    'phrasal-verbs': 'Formal English & Fixed Expressions',
    'collocations': 'Formal English & Fixed Expressions',
    'trends-data': 'IELTS Writing Themes I',
    'opinion-argument': 'IELTS Writing Themes I',
    'education-learning': 'IELTS Writing Themes I',
    'work-career': 'IELTS Writing Themes I',
    'environment-sustainability': 'IELTS Writing Themes II',
    'technology-modern-life': 'IELTS Writing Themes II',
    'travel-society-culture': 'IELTS Writing Themes II',
    'health-lifestyle': 'IELTS Writing Themes II',
    'precision-upgrades': 'Mind, Emotion & Description',
    'essay-power-words': 'Academic Writing Toolkit',
    'society-mind-rhetoric': 'Scale, Change & Society',
    'hedging-likelihood': 'Academic Writing Toolkit II',
    'cause-consequence': 'Academic Writing Toolkit II',
    'connectors-time-sequence': 'Academic Writing Toolkit II',
    'difficulty-risk': 'Academic Writing Toolkit II',
    'proactive-action': 'Vivid Description & Communication',
    'quantity-degree': 'Vivid Description & Communication',
    'vivid-everyday': 'Vivid Description & Communication',
    'communication-disclosure': 'Vivid Description & Communication',
    'cognitive-verbs': 'Cognition, Logic & Research',
    'research-inquiry': 'Cognition, Logic & Research',
    'critical-reasoning': 'Cognition, Logic & Research',
    'memory-perception': 'Cognition, Logic & Research',
    'academic-connectors-iii': 'Academic Connectors III',
    'emphasis-contrast': 'Academic Connectors III',
    'cause-purpose': 'Academic Connectors III',
    'summary-conclusion': 'Academic Connectors III',
    'business-finance': 'Career, Business & Leadership',
    'workplace-communication': 'Career, Business & Leadership',
    'leadership-management': 'Career, Business & Leadership',
    'career-growth': 'Career, Business & Leadership',
    'work-tasks': 'Workplace Tasks & Formal Language',
    'general-useful-verbs': 'Workplace Tasks & Formal Language',
    'formal-register-ii': 'Workplace Tasks & Formal Language',
    'governance-law': 'Governance, Economy & Society',
    'economy-trade': 'Governance, Economy & Society',
    'social-justice': 'Governance, Economy & Society',
    'growth-expansion': 'Governance, Economy & Society',
    'personality-traits-ii': 'Personality, Relationships & Conflict',
    'interpersonal-relationships': 'Personality, Relationships & Conflict',
    'conflict-resolution': 'Personality, Relationships & Conflict',
    'decision-making': 'Personality, Relationships & Conflict',
    'everyday-idioms': 'Everyday Life, Money & Idioms',
    'money-shopping': 'Everyday Life, Money & Idioms',
    'food-health': 'Everyday Life, Money & Idioms',
    'tech-digital-life': 'Science, Tech & Innovation',
    'science-innovation': 'Science, Tech & Innovation',
    'digital-communication': 'Science, Tech & Innovation',
    'ai-automation': 'Science, Tech & Innovation',
    'climate-weather': 'Nature, Climate & Energy',
    'nature-wildlife': 'Nature, Climate & Energy',
    'energy-resources-ii': 'Nature, Climate & Energy',
    'travel-experiences': 'Travel, Culture & Urban Life',
    'cultural-diversity': 'Travel, Culture & Urban Life',
    'urban-development': 'Travel, Culture & Urban Life',
    'lifestyle-habits': 'Lifestyle, Leisure & Wellbeing',
    'leisure-hobbies': 'Lifestyle, Leisure & Wellbeing',
    'health-wellbeing-ii': 'Lifestyle, Leisure & Wellbeing',
    'motivation-ambition': 'Lifestyle, Leisure & Wellbeing',
    'storytelling-narrative': 'Storytelling, Humour & Persuasion',
    'humor-wit': 'Storytelling, Humour & Persuasion',
    'persuasion-rhetoric-ii': 'Storytelling, Humour & Persuasion',
    'size-shape': 'Description: Size, Sound & Movement',
    'sound-light': 'Description: Size, Sound & Movement',
    'movement-action': 'Description: Size, Sound & Movement',
    'comparison-contrast': 'Habits, Comparison & Politeness',
    'habits-routines': 'Habits, Comparison & Politeness',
    'risk-caution': 'Habits, Comparison & Politeness',
    'politeness-formality': 'Habits, Comparison & Politeness',
    'core-action-verbs': 'Essential Verbs',
    'everyday-verbs-ii': 'Essential Verbs',
    'movement-position-verbs': 'Essential Verbs',
    'communication-basic': 'People & Relationships',
    'family-people': 'People & Relationships',
    'describing-people-basic': 'People & Relationships',
    'feelings-emotions-basic': 'Mind & Feelings',
    'home-household': 'Home & Daily Life',
    'food-drink-basic': 'Home & Daily Life',
    'time-calendar': 'Time & Description',
    'weather-nature-basic': 'The Natural World',
    'body-health-basic': 'Body & Health',
    'places-transport-basic': 'Out & About',
    'numbers-school-basic': 'Numbers & Learning',
    'colours-shapes-basic': 'Numbers & Learning',
    'sports-hobbies-basic': 'Sports & Hobbies',
    'complex-emotions': 'Emotions in Depth',
    'personality-character-inter': 'Personality & Character',
    'social-issues-inter': 'Society & Social Issues',
    'work-career-inter': 'Work & Career',
    'environment-inter': 'Environment & Climate',
    'health-medicine-inter': 'Health & Medicine',
    'technology-media-inter': 'Technology & Media',
    'academic-language-inter': 'Academic Language & Writing',
    'food-culture-inter': 'Food, Nutrition & Culture',
    'travel-culture-inter': 'Travel, Culture & Society',
    'education-society-inter': 'Education & Society',
    'law-justice-inter': 'Society & Social Issues',
    'psychology-behaviour-inter': 'Mind, Behaviour & Psychology',
    'communication-language-inter': 'Language & Communication',
    'economics-finance-inter': 'Economics & Finance',
    'global-issues-inter': 'Politics & Global Affairs',
    'arts-culture-inter': 'Arts, Media & Culture',
    'science-discovery-inter': 'Science & Innovation',
    'urban-architecture-inter': 'Cities & Urban Life',
    'ethics-philosophy-inter': 'Society & Social Issues',
    'relationships-society-inter': 'Personality & Character',
    'media-journalism-inter': 'Media & Journalism',
    'health-lifestyle-inter': 'Health & Medicine',
    'abstract-thought-c1': 'Mind & Abstract Thought',
    'rhetoric-persuasion-c1': 'Storytelling, Humour & Persuasion',
    'advanced-vocab-c1': 'Precision & Literary Language',
    'social-change-c1': 'Society, Rights & Change',
    'human-nature-c1': 'Society, Rights & Change',
    'academic-c1-advanced': 'Academic Register & Style',
    'environment-c1': 'Nature, Climate & Energy',
    'globalisation-c1': 'Global Power & Economy',
    'power-politics-c1': 'Global Power & Economy',
    'cognition-mind-c1': 'Mind & Abstract Thought',
    'language-linguistics-c1': 'Academic Register & Style',
    'medicine-biology-c1': 'Science, Research & Medicine',
    'technology-future-c1': 'Science, Tech & Innovation',
    'history-civilisation-c1': 'Arts, History & Culture',
    'arts-expression-c1': 'Arts, History & Culture',
    'philosophy-thought-c2': 'Philosophy & Critical Thought',
    'advanced-adjectives-c2': 'Advanced Adjectives',
    'advanced-verbs-c2': 'Advanced Verbs & Nouns',
    'advanced-nouns-c2': 'Advanced Verbs & Nouns',
    'c2-expressions': 'C2 Finishing Sets',
    'emotions-b-extended': 'Emotions in Depth',
    'describing-actions-b': 'Action & Process Verbs',
    'work-society-b2-extended': 'Work & Career',
    'nature-landscape-b2': 'Environment & Climate',
    'language-communication-b2': 'Language & Communication',
    'politics-governance-b2': 'Politics & Global Affairs',
    'academic-style-c1b': 'Academic Register & Style',
    'ielts-writing-c1-ext': 'IELTS Essay Mastery',
    'science-tech-b2-ext': 'Science & Innovation',
    'health-body-b2-ext': 'Health & Medicine',
    'descriptive-adjectives-c1': 'Advanced Adjectives',
    'idioms-phrases-b2': 'Idioms & Collocations',
    'environment-sustainability-c1': 'Nature, Climate & Energy',
    'academic-verbs-c1': 'Academic Register & Style',
    'literary-descriptive-c2': 'Precision & Literary Language',
    'formal-nouns-c1b': 'Formal Nouns & Qualifiers',
    'arts-media-b2': 'Arts, Media & Culture',
    'philosophy-ethics-c1-ext': 'Philosophy & Critical Thought',
    'geography-demography-b2': 'Politics & Global Affairs',
    'business-economics-c1': 'Career, Business & Leadership',
    'social-human-rights-c1': 'Society, Rights & Change',
    'verbs-precise-b2': 'Action & Process Verbs',
    'cognition-learning-c1': 'Mind, Behaviour & Psychology',
    'idioms-c1-complex': 'Idioms & Collocations',
    'c2-precision-words': 'Precision & Literary Language',
    'crime-justice-c1': 'Governance, Economy & Society',
    'personality-adjectives-c1': 'Advanced Adjectives',
    'academic-nouns-b2': 'Academic Language & Writing',
    'verbs-b2-advanced': 'Verbs for Writing & Analysis',
    'complex-sentence-connectors': 'Connectors & Discourse Markers',
    'collocations-formal-c1': 'Academic Language & Writing',
    'global-issues-c1b': 'Global Power & Economy',
    'word-formation-b2': 'Language & Communication',
    'common-adjectives-b1b': 'Quality & Degree Adjectives',
    'mind-emotion-c1-ext': 'Mind & Abstract Thought',
    'education-learning-b2': 'Education & Society',
    'housing-urban-b2': 'Cities & Urban Life',
    'c2-final-vocab': 'C2 Finishing Sets',
    'technology-digital-b2': 'Technology & Media',
    'food-culture-ext': 'Food, Nutrition & Culture',
    'travel-tourism-b2': 'Travel, Culture & Society',
    'advanced-connectors-c1-final': 'Academic Connectors III',
    'social-media-comm-b2': 'Media & Journalism',
    'science-research-c1': 'Science, Research & Medicine',
    'abstract-concepts-c1-final': 'Philosophy & Critical Thought',
    'common-verbs-b1-ext': 'Action & Process Verbs',
    'formal-adverbs-c1-ext': 'Formal Nouns & Qualifiers',
    'complex-nouns-b2-final': 'B2 Noun Bank',
    'adjectives-b2-quality': 'Quality & Degree Adjectives',
    'final-nouns-c1': 'Formal Nouns & Qualifiers',
    'core-ielts-vocab-final': 'B2 Milestone Sets',
    'final-advanced-b2': 'B2 Milestone Sets',
    'key-transitions-b2-final': 'Connectors & Discourse Markers',
    'additional-b2-vocab': 'B2 Milestone Sets',
    'ielts-essay-vocab': 'IELTS Essay Mastery',
    'b2-nouns-final-set': 'B2 Noun Bank',
    'c1-writing-toolkit': 'IELTS Essay Mastery',
    'final-20-words': 'C2 Finishing Sets',
    'a1plus-body-health': 'Body & Health',
    'a1plus-food-drink': 'Home & Daily Life',
    'a1plus-home-objects': 'Home & Daily Life',
    'a1plus-adjectives-basic': 'Time & Description',
    'a1plus-everyday-verbs': 'Essential Verbs',
    'a1plus-clothes-appearance': 'Home & Daily Life',
    'a1plus-places-transport': 'Out & About',
    'a1plus-school-classroom': 'Numbers & Learning',
    'a1plus-weather-nature': 'The Natural World',
    'a1plus-shopping-money': 'Out & About',
    'a1plus-time-routines': 'Time & Description',
    'a2plus-feelings-opinions': 'Mind & Feelings',
    'a2plus-descriptive-adjectives': 'Time & Description',
    'a2plus-everyday-verbs': 'Essential Verbs',
    'a2plus-travel-places': 'Travel, Culture & Society',
    'a2plus-work-education': 'Work & Career',
    'a2plus-entertainment': 'Sports & Hobbies',
    'b1plus-opinion-discussion': 'Academic Language & Writing',
    'b1plus-society-community': 'Society & Social Issues',
    'b1plus-environment': 'Environment & Climate',
    'b1plus-health-lifestyle': 'Health & Medicine',
    'b1plus-personality': 'Personality & Character',
    'b1plus-technology-media': 'Technology & Media',
    'b1plus-education-study': 'Education & Society',
    'b1plus-economy-work': 'Economics & Finance',
    'c1plus-formal-verbs': 'Formal English & Fixed Expressions',
    'c1plus-adjectives-advanced': 'Mind, Emotion & Description',
    'c1plus-abstract-nouns': 'Formal English & Fixed Expressions',
    'c1plus-literary-expressive': 'Mind, Emotion & Description',
    'c1plus-academic-discourse': 'Academic Writing Toolkit',
    'b2plus-analysis-verbs': 'Verbs for Writing & Analysis',
    'b2plus-nuanced-adjectives': 'Quality & Degree Adjectives',
    'c2plus-rare-adjectives': 'Advanced Lexical Expansion',
    'c2plus-elevated-verbs': 'Advanced Lexical Expansion',
    'c2plus-abstract-nouns-ii': 'Advanced Lexical Expansion',
    'c2plus-idioms-collocations': 'Advanced Lexical Expansion',
    'b2plus-precision-adjectives': 'Precision & Control Vocabulary',
    'b2plus-control-verbs': 'Precision & Control Vocabulary',
    'a2-everyday-essentials': 'Home & Daily Life',
    'c1plus-bias-power-hardship': 'Society, Rights & Change',
}


def seed_and_backfill(apps, schema_editor):
    VocabSection = apps.get_model('vocab', 'VocabSection')
    Category = apps.get_model('vocab', 'Category')

    sections_by_name = {}
    for order, (slug, name, tier) in enumerate(SECTIONS):
        section = VocabSection.objects.create(slug=slug, name=name, tier=tier, order=order)
        sections_by_name[name] = section

    for category in Category.objects.all():
        section_name = CATEGORY_SECTIONS.get(category.slug)
        section = sections_by_name.get(section_name) if section_name else None
        if section:
            category.section = section
            category.save(update_fields=['section'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_grammarsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='categories', to='vocab.vocabsection',
            ),
        ),
        migrations.RunPython(seed_and_backfill, reverse_code=noop),
    ]
