# Generated by Django 5.2.15 on 2026-07-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocab', '0005_alter_grammartopic_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
            ],
            options={
                'ordering': ['order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vocab.grammarlessonblock',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
            ],
            options={
                'ordering': ['order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vocab.grammarquestion',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
            ],
            options={
                'ordering': ['order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vocab.grammartopic',),
        ),
    ]
