# Generated by Django 5.2.15 on 2026-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grammar_map',
            field=models.JSONField(default=dict),
        ),
    ]
